import { en } from './locales/en';
import { es } from './locales/es';
import { fr } from './locales/fr';
import { it } from './locales/it';
import { pt } from './locales/pt';

type Tree = { [key: string]: string | Tree };

export const REVIEW_LANGUAGES = {
  es: { name: 'Spanish', variant: 'neutral Latin American', strings: es },
  fr: { name: 'French', variant: 'France', strings: fr },
  it: { name: 'Italian', variant: 'Italy', strings: it },
  pt: { name: 'Portuguese', variant: 'Brazilian', strings: pt },
} as const;

type ReviewLanguage = keyof typeof REVIEW_LANGUAGES;

const SECTION_TITLES: Record<keyof typeof en, string> = {
  languages: 'Language names',
  common: 'Shared messages',
  uiLanguage: 'Language picker',
  login: 'Login page',
  setup: 'Game setup',
  game: 'Game screen',
  help: 'How to Play',
  nav: 'Menu and home page',
  score: 'Score panel',
  postGame: 'Match summary',
  replay: 'Replays',
  leaderboard: 'Leaderboard',
  challenges: 'Challenges page',
  challengeFriend: 'Challenge a friend',
  profile: 'Profile',
  friends: 'Friends',
  stats: 'Stats',
  history: 'Game history',
  achievements: 'Achievements',
  feats: 'Feats',
  tracks: 'Tracks',
  flags: 'Custom flags',
  vocab: 'Vocabulary',
};

function flatten(tree: Tree, prefix = ''): [string, string][] {
  return Object.entries(tree).flatMap(([key, value]) => {
    const path = prefix ? `${prefix}.${key}` : key;
    return typeof value === 'string' ? [[path, value] as [string, string]] : flatten(value, path);
  });
}

function cell(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\|/g, '\\|')
    .replace(/\n/g, '<br>');
}

export function buildReviewDoc(lang: ReviewLanguage): string {
  const { name, variant, strings } = REVIEW_LANGUAGES[lang];
  const lines = [
    `# ${name} translations (${variant})`,
    '',
    '<!-- Generated by `npm run i18n:review`. Edit the locale files, not this page. -->',
    '',
    `Source file: [\`src/i18n/locales/${lang}.ts\`](../../src/i18n/locales/${lang}.ts)`,
    '',
    'When reviewing:',
    '- Keep `{{name}}`-style placeholders exactly as they are; the app fills them in.',
    '- Keep tags like `<name>…</name>` or `<green>…</green>` around the same words; they add links and colours.',
    '- To suggest a change, comment on the pull request with the key from the first column.',
    '',
  ];
  for (const section of Object.keys(SECTION_TITLES) as (keyof typeof en)[]) {
    const translated = new Map(flatten(strings[section] as Tree));
    lines.push(`## ${SECTION_TITLES[section]}`, '', `| Key | English | ${name} |`, '|---|---|---|');
    for (const [key, english] of flatten(en[section] as Tree)) {
      lines.push(
        `| \`${section}.${key}\` | ${cell(english)} | ${cell(translated.get(key) ?? '')} |`
      );
    }
    lines.push('');
  }
  return lines.join('\n');
}

export function buildReviewIndex(): string {
  const rows = (Object.keys(REVIEW_LANGUAGES) as ReviewLanguage[]).map((lang) => {
    const { name, variant } = REVIEW_LANGUAGES[lang];
    return `- [${name}](./${lang}.md) (${variant})`;
  });
  return [
    '# Translation review',
    '',
    '<!-- Generated by `npm run i18n:review`. -->',
    '',
    'Each page lists every interface string in English next to its translation, grouped by screen.',
    '',
    ...rows,
    '',
  ].join('\n');
}
