import fs from 'fs';
import { normalizeWord, BANNED_WORDS, loadFrequencies } from './dictUtils.mjs';

// Base dictionary templates & fallback semantic generators for common roots
const EN_DEFS = {
  about: { pos: 'prep/adv', def: 'On the subject of or concerning someone or something.' },
  above: { pos: 'prep/adv', def: 'At a higher place or position than something else.' },
  actor: { pos: 'noun', def: 'A person whose profession is acting on stage or screen.' },
  acute: { pos: 'adj', def: 'Present or experienced to a severe or intense degree.' },
  admit: { pos: 'verb', def: 'To confess to be true or to be the case.' },
  adopt: { pos: 'verb', def: 'To legally take another child and bring it up as own.' },
  adult: { pos: 'noun/adj', def: 'A person who is fully grown or developed.' },
  after: { pos: 'prep/adv', def: 'In the time following an event or another period.' },
  again: { pos: 'adv', def: 'Another time; once more; returned to previous position.' },
  agent: { pos: 'noun', def: 'A person who acts on behalf of another person or group.' },
  agree: { pos: 'verb', def: 'To have the same opinion about something with another.' },
  ahead: { pos: 'adv', def: 'Further forward in space or time; in the lead.' },
  alarm: { pos: 'noun', def: 'An anxious awareness of danger or a warning sound.' },
  album: { pos: 'noun', def: 'A collection of audio recordings or photographs in book.' },
  alert: { pos: 'adj/noun', def: 'Quick to notice any unusual and potentially dangerous circumstances.' },
  alien: { pos: 'noun/adj', def: 'Belonging to a foreign country or another planet entirely.' },
  align: { pos: 'verb', def: 'To place or arrange things in a straight line.' },
  alike: { pos: 'adj/adv', def: 'Similar to each other in appearance or character.' },
  alive: { pos: 'adj', def: 'Living and not dead; full of energy and active.' },
  allow: { pos: 'verb', def: 'To give the necessary permission for someone to do.' },
  alone: { pos: 'adj/adv', def: 'Having no one else present; on one own.' },
  along: { pos: 'prep/adv', def: 'Moving in a constant direction on or beside something.' },
  alter: { pos: 'verb', def: 'To change or cause to change in character or composition.' },
  amber: { pos: 'noun/adj', def: 'Hard translucent fossilized resin or a warm honey-yellow color.' },
  amend: { pos: 'verb', def: 'To make minor changes in order to make fairer or better.' },
  among: { pos: 'prep', def: 'Situated more or less centrally in relation to several other things.' },
  angel: { pos: 'noun', def: 'A spiritual being believed to act as an attendant of God.' },
  anger: { pos: 'noun', def: 'A strong feeling of annoyance, displeasure, or hostility.' },
  angle: { pos: 'noun', def: 'The space between two intersecting lines or surfaces.' },
  angry: { pos: 'adj', def: 'Feeling or showing strong annoyance, displeasure, or hostility.' },
  anime: { pos: 'noun', def: 'A style of Japanese film and television animation.' },
  ankle: { pos: 'noun', def: 'The joint connecting the foot with the leg.' },
  apart: { pos: 'adv', def: 'Separated by a specified distance in space or time.' },
  apple: { pos: 'noun', def: 'A round fruit with firm white flesh and red or green skin.' },
  apply: { pos: 'verb', def: 'To make a formal application or put into practical use.' },
  apron: { pos: 'noun', def: 'A protective garment worn over the front of clothes.' },
  arena: { pos: 'noun', def: 'A level area surrounded by seating for sports or entertainment.' },
  argue: { pos: 'verb', def: 'To exchange or express diverging or opposite views heatedly.' },
  arise: { pos: 'verb', def: 'To emerge, become apparent, or originate from a source.' },
  armor: { pos: 'noun', def: 'Metal coverings worn by soldiers to protect the body.' },
  array: { pos: 'noun', def: 'An impressive display or range of a particular type of thing.' },
  arrow: { pos: 'noun', def: 'A weapon consisting of a shaft with a pointed head.' },
  asset: { pos: 'noun', def: 'A useful or valuable quality, person, or thing.' },
  audio: { pos: 'noun/adj', def: 'Sound, especially when recorded, transmitted, or reproduced.' },
  audit: { pos: 'noun/verb', def: 'An official inspection of an organization accounts or systems.' },
  avoid: { pos: 'verb', def: 'To keep away from or stop oneself from doing something.' },
  await: { pos: 'verb', def: 'To wait for an event or person with anticipation.' },
  awake: { pos: 'adj/verb', def: 'Not asleep; conscious and aware of one surroundings.' },
  award: { pos: 'noun/verb', def: 'A prize or other mark of recognition given in honor.' },
  aware: { pos: 'adj', def: 'Having knowledge or perception of a situation or fact.' },
  bacon: { pos: 'noun', def: 'Cured meat from the sides or back of a pig.' },
  badge: { pos: 'noun', def: 'A small piece of metal or plastic showing membership or rank.' },
  baker: { pos: 'noun', def: 'A person who makes and sells bread and cakes.' },
  basic: { pos: 'adj', def: 'Forming an essential foundation or starting point of something.' },
  basin: { pos: 'noun', def: 'A wide, open container used for holding liquids or washing.' },
  basis: { pos: 'noun', def: 'The underlying support or foundation for an idea or system.' },
  batch: { pos: 'noun', def: 'A quantity of goods produced at one time together.' },
  beach: { pos: 'noun', def: 'A sandy or pebbly shore by the ocean or lake.' },
  beard: { pos: 'noun', def: 'A growth of hair on the chin and cheeks.' },
  beast: { pos: 'noun', def: 'An animal, especially a large or dangerous four-footed one.' },
  begin: { pos: 'verb', def: 'To perform or undergo the first part of an action.' },
  being: { pos: 'noun', def: 'Existence or the nature and essence of a person.' },
  belly: { pos: 'noun', def: 'The front part of the human trunk below the ribs.' },
  below: { pos: 'prep/adv', def: 'At a lower level or layer than something else.' },
  bench: { pos: 'noun', def: 'A long seat for several people, typically made of wood.' },
  berry: { pos: 'noun', def: 'A small round juicy fruit without a stone.' },
  birth: { pos: 'noun', def: 'The emergence of a baby or other young from its mother.' },
  black: { pos: 'adj/noun', def: 'Of the very darkest color owing to the absence of light.' },
  blade: { pos: 'noun', def: 'The flat cutting edge of a knife, tool, or sword.' },
  blame: { pos: 'verb/noun', def: 'To assign responsibility for a fault or wrong.' },
  blank: { pos: 'adj/noun', def: 'Bare, empty, or having no marks or expression.' },
  blast: { pos: 'noun/verb', def: 'A destructive wave of highly compressed air from an explosion.' },
  blaze: { pos: 'noun/verb', def: 'A very large and fiercely burning fire producing heat.' },
  blend: { pos: 'verb/noun', def: 'To mix together thoroughly into a single uniform substance.' },
  blind: { pos: 'adj', def: 'Unable to see because of injury, disease, or birth.' },
  block: { pos: 'noun/verb', def: 'A large solid piece of hard material or an obstruction.' },
  blood: { pos: 'noun', def: 'The red liquid circulating in the arteries and veins.' },
  bloom: { pos: 'noun/verb', def: 'A flower or the state of producing sweet flowers.' },
  board: { pos: 'noun', def: 'A long, thin, flat piece of wood or hard material.' },
  boast: { pos: 'verb', def: 'To talk with excessive pride and self-satisfaction about oneself.' },
  bonus: { pos: 'noun', def: 'An amount of money or reward added to normal expectations.' },
  boost: { pos: 'verb/noun', def: 'To help or encourage something to increase or improve.' },
  booth: { pos: 'noun', def: 'A small temporary tent or structure used at markets or fairs.' },
  bound: { pos: 'adj/verb', def: 'Restricted, destined, or leaping forward with springy steps.' },
  brain: { pos: 'noun', def: 'The organ that coordinates sensation, thought, and nervous activity.' },
  brake: { pos: 'noun/verb', def: 'A device for slowing or stopping a moving vehicle.' },
  brand: { pos: 'noun', def: 'A type of product manufactured by a particular company.' },
  brass: { pos: 'noun', def: 'A yellow alloy of copper and zinc used in instruments.' },
  brave: { pos: 'adj', def: 'Ready to face and endure danger without showing fear.' },
  bread: { pos: 'noun', def: 'Food made of flour, water, and yeast mixed and baked.' },
  break: { pos: 'verb/noun', def: 'To separate into pieces as a result of a blow or shock.' },
  brick: { pos: 'noun', def: 'A small rectangular block of fired clay used in building.' },
  bride: { pos: 'noun', def: 'A woman on her wedding day or just before it.' },
  brief: { pos: 'adj', def: 'Of short duration; concise in use of spoken words.' },
  bring: { pos: 'verb', def: 'To take or carry someone or something to a place.' },
  broad: { pos: 'adj', def: 'Having an ample distance from side to side; wide.' },
  brown: { pos: 'adj/noun', def: 'Of a color produced by mixing red, yellow, and black.' },
  brush: { pos: 'noun/verb', def: 'An implement with bristles used for cleaning or painting.' },
  buddy: { pos: 'noun', def: 'A close friend or companion in work or leisure.' },
  build: { pos: 'verb', def: 'To construct something by putting parts or material together.' },
  bunch: { pos: 'noun', def: 'A number of things grouped together in a cluster.' },
  burst: { pos: 'verb/noun', def: 'To break open or apart suddenly and violently.' },
  buyer: { pos: 'noun', def: 'A person who makes a purchase of goods or services.' },
  cabin: { pos: 'noun', def: 'A small wooden shelter or house in a wild area.' },
  cable: { pos: 'noun', def: 'A thick rope of wire or fiber used for construction.' },
  camel: { pos: 'noun', def: 'A large long-necked mammal with one or two humps.' },
  candy: { pos: 'noun', def: 'A sweet food made with sugar or syrup and flavoring.' },
  canoe: { pos: 'noun', def: 'A narrow boat with pointed ends propelled by paddles.' },
  cargo: { pos: 'noun', def: 'Goods carried on a ship, aircraft, or motor vehicle.' },
  carry: { pos: 'verb', def: 'To support and move someone or something while walking.' },
  catch: { pos: 'verb/noun', def: 'To intercept and hold something moving through the air.' },
  cause: { pos: 'noun/verb', def: 'A person or thing that gives rise to an action.' },
  chain: { pos: 'noun', def: 'A series of linked metal rings used for fastening.' },
  chair: { pos: 'noun', def: 'A separate seat for one person, with a back and legs.' },
  chalk: { pos: 'noun', def: 'A soft white limestone used for writing on blackboards.' },
  champ: { pos: 'noun', def: 'A person who has defeated all rivals in competition.' },
  charm: { pos: 'noun/verb', def: 'The power or quality of giving delight or a magical spell.' },
  chart: { pos: 'noun/verb', def: 'A sheet of information in the form of a table or graph.' },
  chase: { pos: 'verb/noun', def: 'To pursue in order to catch or overtake someone.' },
  cheap: { pos: 'adj', def: 'Low in price, especially in relation to value received.' },
  cheat: { pos: 'verb/noun', def: 'To act dishonestly or unfairly in order to gain advantage.' },
  check: { pos: 'verb/noun', def: 'To examine something in order to determine its state or accuracy.' },
  cheer: { pos: 'noun/verb', def: 'A shout of encouragement, praise, or friendly celebration.' },
  chest: { pos: 'noun', def: 'The front surface of a person body between neck and stomach.' },
  chief: { pos: 'noun/adj', def: 'A leader or ruler of a people, clan, or organization.' },
  child: { pos: 'noun', def: 'A young human being below the age of puberty.' },
  chill: { pos: 'noun/adj', def: 'An unpleasant feeling of coldness in the air or body.' },
  chord: { pos: 'noun', def: 'A group of musical notes sounded together in harmony.' },
  claim: { pos: 'verb/noun', def: 'To state or assert that something is the case definitively.' },
  class: { pos: 'noun', def: 'A set or category of things having some property in common.' },
  clean: { pos: 'adj/verb', def: 'Free from dirt, marks, or stains; unsoiled and neat.' },
  clear: { pos: 'adj/verb', def: 'Easy to perceive, understand, or interpret clearly and plainly.' },
  clerk: { pos: 'noun', def: 'A person employed in an office or bank to keep records.' },
  click: { pos: 'noun/verb', def: 'A short, sharp sound made by an electronic switch or mouse.' },
  cliff: { pos: 'noun', def: 'A steep, high rock face, especially at the edge of the sea.' },
  climb: { pos: 'verb', def: 'To go upward or ascend using hands and feet.' },
  cloak: { pos: 'noun', def: 'An outdoor overgarment, typically sleeveless, that hangs loosely.' },
  clock: { pos: 'noun', def: 'A mechanical or electrical device for measuring and showing time.' },
  close: { pos: 'adj/verb', def: 'A short distance away or having strong affection and intimacy.' },
  cloth: { pos: 'noun', def: 'Woven or felted fabric made from wool, cotton, or fibers.' },
  cloud: { pos: 'noun', def: 'A visible mass of condensed water vapor floating in the sky.' },
  clown: { pos: 'noun', def: 'A comic entertainer wearing traditional costume and exaggerated makeup.' },
  coach: { pos: 'noun/verb', def: 'An instructor or trainer in sports or performing arts.' },
  coast: { pos: 'noun', def: 'The part of the land adjoining or near the sea.' },
  color: { pos: 'noun', def: 'The property possessed by an object of producing visual sensations.' },
  comet: { pos: 'noun', def: 'A celestial object consisting of a nucleus of ice and dust.' },
  coral: { pos: 'noun/adj', def: 'A hard stony substance formed by marine coelenterate skeletons.' },
  couch: { pos: 'noun', def: 'A long upholstered piece of furniture for several people to sit.' },
  count: { pos: 'verb', def: 'To determine the total number of a collection of items.' },
  court: { pos: 'noun', def: 'A place where legal justice is administered by a judge.' },
  cover: { pos: 'verb/noun', def: 'To put something over or upon in order to protect or hide.' },
  crack: { pos: 'noun/verb', def: 'A line on the surface of something along which it has split.' },
  craft: { pos: 'noun', def: 'An activity involving skill in making things by hand.' },
  crane: { pos: 'noun', def: 'A tall machine with a hoist rope used for lifting heavy items.' },
  crash: { pos: 'verb/noun', def: 'To collide violently with an obstacle or another vehicle.' },
  cream: { pos: 'noun', def: 'The thick white or pale yellow fatty liquid of milk.' },
  creek: { pos: 'noun', def: 'A stream, brook, or minor tributary of a river.' },
  crisp: { pos: 'adj', def: 'Giving a pleasingly firm, dry, and brittle crunch when bitten.' },
  cross: { pos: 'noun/verb', def: 'A mark or structure consisting of an upright and a transverse bar.' },
  crowd: { pos: 'noun', def: 'A large number of people gathered together in a disorganized way.' },
  crown: { pos: 'noun', def: 'A circular ornamental headdress worn by a monarch as a symbol.' },
  crush: { pos: 'verb', def: 'To deform, pulverize, or force inwards by compressing forcefully.' },
  curve: { pos: 'noun/verb', def: 'A line or outline which gradually deviates from being straight.' },
  cycle: { pos: 'noun', def: 'A series of events that are regularly repeated in the same order.' },
  dance: { pos: 'noun/verb', def: 'A series of rhythmic steps and movements matched to music.' },
  delta: { pos: 'noun', def: 'A triangular tract of sediment deposited at the mouth of a river.' },
  depth: { pos: 'noun', def: 'The distance from the top or surface to the bottom of something.' },
  digit: { pos: 'noun', def: 'Any of the numerals from zero to nine, or a finger or toe.' },
  diner: { pos: 'noun', def: 'A person who is eating dinner, or a small casual restaurant.' },
  disco: { pos: 'noun', def: 'A club or party at which people dance to pop music.' },
  ditch: { pos: 'noun', def: 'A narrow channel dug at the side of a road or field.' },
  diver: { pos: 'noun', def: 'A person who dives underwater using specialized breathing apparatus.' },
  donor: { pos: 'noun', def: 'A person who provides a gift of money, blood, or an organ.' },
  doubt: { pos: 'noun/verb', def: 'A feeling of uncertainty or lack of conviction about something.' },
  draft: { pos: 'noun/verb', def: 'A preliminary version of a piece of writing or a cool breeze.' },
  drain: { pos: 'verb/noun', def: 'To cause the water or other liquid in something to run out.' },
  drama: { pos: 'noun', def: 'A play for theater, radio, or television, or an exciting event.' },
  dream: { pos: 'noun/verb', def: 'A series of thoughts, images, and sensations occurring in sleep.' },
  dress: { pos: 'noun/verb', def: 'A one-piece garment for a woman or girl covering body and legs.' },
  drift: { pos: 'verb/noun', def: 'To be carried slowly along by a current of air or water.' },
  drink: { pos: 'verb/noun', def: 'To swallow liquid down the throat for nourishment or thirst.' },
  drive: { pos: 'verb/noun', def: 'To operate and control the direction and speed of a motor vehicle.' },
  drone: { pos: 'noun', def: 'An unmanned aircraft or ship guided remotely or by computers.' },
  drown: { pos: 'verb', def: 'To die through submersion in and inhalation of water or liquid.' },
  dwarf: { pos: 'noun/adj', def: 'A mythical short humanoid creature renowned for underground craftsmanship.' },
  eagle: { pos: 'noun', def: 'A large bird of prey with a massive hooked bill and broad wings.' },
  early: { pos: 'adj/adv', def: 'Happening or done before the usual or expected time.' },
  earth: { pos: 'noun', def: 'The planet on which we live; the world or soil.' },
  elbow: { pos: 'noun', def: 'The joint between the forearm and the upper arm.' },
  elder: { pos: 'adj/noun', def: 'Of greater age or senior status in a community or family.' },
  elect: { pos: 'verb', def: 'To choose someone to hold public office by voting in an election.' },
  elite: { pos: 'noun/adj', def: 'A select group that is superior in abilities or qualities.' },
  ember: { pos: 'noun', def: 'A small piece of burning or glowing coal or wood in a dying fire.' },
  empty: { pos: 'adj/verb', def: 'Containing nothing; not filled or occupied by anything.' },
  enemy: { pos: 'noun', def: 'A person who is actively opposed or hostile to someone or something.' },
  enjoy: { pos: 'verb', def: 'To take delight or pleasure in an activity or occasion.' },
  enter: { pos: 'verb', def: 'To come or go into a place or start participating in an event.' },
  entry: { pos: 'noun', def: 'An act of going or coming in, or an item written in a list.' },
  equal: { pos: 'adj/noun', def: 'Being the same in quantity, size, degree, or value as another.' },
  erase: { pos: 'verb', def: 'To rub out or remove writing or recorded marks cleanly.' },
  error: { pos: 'noun', def: 'A mistake or the state or condition of being wrong.' },
  event: { pos: 'noun', def: 'A thing that happens, especially one of importance or note.' },
  exact: { pos: 'adj', def: 'Not approximated in any way; strictly correct and precise.' },
  fable: { pos: 'noun', def: 'A short story, typically with animals as characters, conveying a moral.' },
  facet: { pos: 'noun', def: 'One side of something many-sided, especially of a cut gem.' },
  faith: { pos: 'noun', def: 'Complete trust or confidence in someone or something, or religious belief.' },
  fancy: { pos: 'adj/verb', def: 'Elaborate in structure or decoration, or to feel a desire for.' },
  feast: { pos: 'noun/verb', def: 'A large meal, typically one in celebration of something special.' },
  fence: { pos: 'noun', def: 'A barrier enclosing an area of ground to prevent entry or escape.' },
  fiber: { pos: 'noun', def: 'A thread or filament from which a vegetable tissue or mineral is formed.' },
  field: { pos: 'noun', def: 'An area of open land, especially one planted with crops or pasture.' },
  fight: { pos: 'verb/noun', def: 'To take part in a violent struggle involving physical force.' },
  final: { pos: 'adj/noun', def: 'Coming at the end of a series; ultimate or decisive.' },
  flame: { pos: 'noun', def: 'A hot glowing body of ignited gas produced by something on fire.' },
  flash: { pos: 'noun/verb', def: 'A sudden brief burst of bright light or sudden brief display.' },
  flask: { pos: 'noun', def: 'A container or bottle with a narrow neck used in laboratory or travel.' },
  fleet: { pos: 'noun/adj', def: 'A group of ships sailing together, or fast and nimble in movement.' },
  flesh: { pos: 'noun', def: 'The soft substance between the skin and bones of animal bodies.' },
  flock: { pos: 'noun/verb', def: 'A number of birds of one kind feeding, resting, or traveling together.' },
  flood: { pos: 'noun/verb', def: 'An overflow of a large amount of water beyond its normal limits.' },
  floor: { pos: 'noun', def: 'The lower surface of a room, on which one may walk.' },
  flour: { pos: 'noun', def: 'A powder obtained by grinding grain, typically wheat, and used in baking.' },
  flute: { pos: 'noun', def: 'A high-pitched woodwind instrument played by blowing across a side hole.' },
  focus: { pos: 'noun/verb', def: 'The center of interest or activity, or state of clear visual definition.' },
  force: { pos: 'noun/verb', def: 'Strength or energy as an attribute of physical action or movement.' },
  forge: { pos: 'verb/noun', def: 'To make or shape a metal object by heating in a fire and hammering.' },
  forth: { pos: 'adv', def: 'Out and into view, or forward into notice or onward in time.' },
  found: { pos: 'verb', def: 'To establish or originate an institution or organization firmly.' },
  frame: { pos: 'noun/verb', def: 'A rigid structure that surrounds or encloses something such as a picture.' },
  fresh: { pos: 'adj', def: 'Recently made or obtained; not stale, sour, or preserved.' },
  frost: { pos: 'noun', def: 'A deposit of small white ice crystals formed on the ground and objects.' },
  fruit: { pos: 'noun', def: 'The sweet and fleshy product of a tree or other plant that contains seed.' },
  ghost: { pos: 'noun', def: 'An apparition of a dead person which is believed to appear to the living.' },
  giant: { pos: 'noun/adj', def: 'An imaginary being of human form but superhuman size and strength.' },
  glass: { pos: 'noun', def: 'A hard, brittle substance, typically transparent or translucent.' },
  gleam: { pos: 'noun/verb', def: 'To shine brightly, especially with reflected light on a smooth surface.' },
  globe: { pos: 'noun', def: 'The earth, or a spherical model of the earth with land features.' },
  glory: { pos: 'noun', def: 'High renown or honor won by notable achievements in life.' },
  glove: { pos: 'noun', def: 'A covering for the hand made with a separate sheath for each finger.' },
  grace: { pos: 'noun', def: 'Simple elegance or refinement of movement, or courteous goodwill.' },
  grade: { pos: 'noun/verb', def: 'A particular level of rank, quality, proficiency, or value.' },
  grain: { pos: 'noun', def: 'Wheat or any other cultivated cereal crop used as food.' },
  grand: { pos: 'adj', def: 'Magnificent and imposing in appearance, size, or style.' },
  grape: { pos: 'noun', def: 'A smooth-skinned juicy light green or purple berry growing in clusters.' },
  grass: { pos: 'noun', def: 'Vegetation consisting of typically short plants with narrow leaves.' },
  grave: { pos: 'noun/adj', def: 'A hole dug in the ground to receive a coffin, or giving cause for alarm.' },
  great: { pos: 'adj', def: 'Of an extent, amount, or intensity considerably above the normal.' },
  green: { pos: 'adj/noun', def: 'Of the color between blue and yellow in the spectrum; colored like grass.' },
  greet: { pos: 'verb', def: 'To give a polite word or sign of welcome to someone upon meeting.' },
  group: { pos: 'noun/verb', def: 'A number of people or things that are located close together or categorized.' },
  grove: { pos: 'noun', def: 'A small wood, orchard, or group of trees in an open area.' },
  guard: { pos: 'verb/noun', def: 'To watch over in order to protect or control persons or property.' },
  guess: { pos: 'verb/noun', def: 'To estimate or suppose without sufficient information to be sure of being correct.' },
  guest: { pos: 'noun', def: 'A person who is invited to visit someone home or attend an event.' },
  guide: { pos: 'noun/verb', def: 'A person who advises or shows the way to others on a journey.' },
  habit: { pos: 'noun', def: 'A settled or regular tendency or practice, especially one hard to give up.' },
  happy: { pos: 'adj', def: 'Feeling or showing pleasure or contentment in one life circumstances.' },
  harsh: { pos: 'adj', def: 'Unpleasantly rough or jarring to the senses, or unpleasantly severe.' },
  hatch: { pos: 'verb/noun', def: 'To emerge from an egg by breaking through its outer shell.' },
  heart: { pos: 'noun', def: 'The muscular organ in humans and animals that pumps blood through the body.' },
  heavy: { pos: 'adj', def: 'Of great weight; difficult to lift or move due to density.' },
  honey: { pos: 'noun', def: 'A sweet, sticky yellowish-brown fluid made by bees and other insects.' },
  honor: { pos: 'noun/verb', def: 'High respect or great esteem, or adherence to what is right.' },
  horse: { pos: 'noun', def: 'A large plant-eating domesticated mammal with solid hoofs and flowing mane.' },
  hotel: { pos: 'noun', def: 'An establishment providing accommodation, meals, and other services for travelers.' },
  house: { pos: 'noun', def: 'A building for human habitation, especially one that is lived in by a family.' },
  human: { pos: 'adj/noun', def: 'Relating to or characteristic of humankind or individual people.' },
  humor: { pos: 'noun/verb', def: 'The quality of being amusing or comic, especially as expressed in speech.' },
  image: { pos: 'noun', def: 'A representation of the external form of a person or thing in art.' },
  irony: { pos: 'noun', def: 'The expression of meaning through language that signifies the opposite.' },
  issue: { pos: 'noun/verb', def: 'An important topic or problem for debate or discussion in society.' },
  jewel: { pos: 'noun', def: 'A precious stone, typically a single crystal or a piece of cut gemstone.' },
  joint: { pos: 'noun/adj', def: 'A point at which parts of an artificial or natural structure are joined.' },
  judge: { pos: 'noun/verb', def: 'A public official appointed to decide cases in a court of law.' },
  juice: { pos: 'noun', def: 'The liquid part that can be extracted from plant tissue or fruit.' },
  knife: { pos: 'noun', def: 'An instrument composed of a blade fixed into a handle, used for cutting.' },
  knock: { pos: 'verb/noun', def: 'To strike a surface noisily to attract attention, especially a door.' },
  labor: { pos: 'noun/verb', def: 'Work, especially hard physical work done for wages or creation.' },
  lance: { pos: 'noun', def: 'A long weapon for thrusting, having a wooden shaft and pointed steel head.' },
  laser: { pos: 'noun', def: 'A device that generates an intense beam of coherent monochromatic light.' },
  latch: { pos: 'noun/verb', def: 'A metal bar with a catch and lever used for fastening a door or gate.' },
  laugh: { pos: 'verb/noun', def: 'To make the spontaneous sounds and movements of the face and body showing amusement.' },
  layer: { pos: 'noun/verb', def: 'A sheet, quantity, or thickness of material spread over a surface.' },
  learn: { pos: 'verb', def: 'To gain or acquire knowledge of or skill in something by study or experience.' },
  lemon: { pos: 'noun', def: 'A yellow, oval citrus fruit with thick skin and fragrant, acid juice.' },
  level: { pos: 'noun/adj', def: 'A horizontal plane or line with respect to the distance above or below.' },
  light: { pos: 'noun/adj', def: 'The natural agent that stimulates sight and makes things visible to eyes.' },
  limit: { pos: 'noun/verb', def: 'A point or level beyond which something does not or may not extend.' },
  linen: { pos: 'noun', def: 'Cloth woven from flax, or articles such as sheets made of linen.' },
  logic: { pos: 'noun', def: 'Reasoning conducted or assessed according to strict principles of validity.' },
  lucky: { pos: 'adj', def: 'Having, bringing, or resulting from good luck or fortunate circumstances.' },
  lunch: { pos: 'noun/verb', def: 'A meal eaten in the middle of the day, typically between breakfast and dinner.' },
  magic: { pos: 'noun/adj', def: 'The power of apparently influencing events by using mysterious or supernatural forces.' },
  major: { pos: 'adj/noun', def: 'Important, serious, or significant; greater in importance or degree.' },
  mango: { pos: 'noun', def: 'A fleshy, oval, yellowish-red tropical fruit that is eaten ripe or used green.' },
  manor: { pos: 'noun', def: 'A large country house with lands; the principal house of a landed estate.' },
  march: { pos: 'verb/noun', def: 'To walk in a military manner with a regular measured tread.' },
  match: { pos: 'noun/verb', def: 'A contest in which people or teams compete against each other in sports.' },
  metal: { pos: 'noun', def: 'A solid material that is typically hard, shiny, malleable, and conducts electricity.' },
  minor: { pos: 'adj/noun', def: 'Lesser in importance, seriousness, or significance than other things.' },
  model: { pos: 'noun/verb', def: 'A three-dimensional representation of a person or thing or of a proposed structure.' },
  money: { pos: 'noun', def: 'A current medium of exchange in the form of coins and banknotes.' },
  month: { pos: 'noun', def: 'Each of the twelve named periods into which a year is divided.' },
  moral: { pos: 'adj/noun', def: 'Concerned with the principles of right and wrong behavior and goodness.' },
  motor: { pos: 'noun', def: 'A machine, especially one powered by electricity or internal combustion, that supplies power.' },
  mount: { pos: 'verb/noun', def: 'To climb up or on to a higher place, horse, or platform.' },
  mouse: { pos: 'noun', def: 'A small rodent with pointed snout, relatively large ears, and long tail.' },
  mouth: { pos: 'noun', def: 'The opening and cavity in the lower part of the face surrounded by lips.' },
  music: { pos: 'noun', def: 'Vocal or instrumental sounds combined in such a way as to produce beauty of form.' },
  night: { pos: 'noun', def: 'The period of darkness in each twenty-four hours from sunset to sunrise.' },
  noble: { pos: 'adj/noun', def: 'Belonging to a hereditary class with high social or political status.' },
  noise: { pos: 'noun', def: 'A sound, especially one that is loud or unpleasant or that causes disturbance.' },
  novel: { pos: 'noun/adj', def: 'A fictitious prose narrative of book length, typically representing characters.' },
  nurse: { pos: 'noun/verb', def: 'A person trained to care for the sick or infirm, especially in a hospital.' },
  ocean: { pos: 'noun', def: 'A very large expanse of sea, in particular each of the main areas.' },
  offer: { pos: 'verb/noun', def: 'To present something for someone to accept or reject as desired.' },
  olive: { pos: 'noun/adj', def: 'A small oval fruit with a hard pit and bitter flesh yielding oil.' },
  opera: { pos: 'noun', def: 'A dramatic work in one or more acts, set to music for singers.' },
  orbit: { pos: 'noun/verb', def: 'The curved path of a celestial object or spacecraft around a star or planet.' },
  order: { pos: 'noun/verb', def: 'The arrangement or disposition of people or things according to a particular sequence.' },
  organ: { pos: 'noun', def: 'A part of an organism that is typically self-contained and has a specific vital function.' },
  paint: { pos: 'noun/verb', def: 'A colored substance that is spread over a surface and dries to leave a thin coating.' },
  panel: { pos: 'noun', def: 'A flat or curved component, typically rectangular, that forms part of a surface.' },
  paper: { pos: 'noun', def: 'Material manufactured in thin sheets from the pulp of wood or other fibers.' },
  party: { pos: 'noun', def: 'A social gathering of invited guests, typically involving eating, drinking, and entertainment.' },
  peace: { pos: 'noun', def: 'Freedom from disturbance; tranquility, or a state of mutual harmony.' },
  peach: { pos: 'noun', def: 'A round stone fruit with juicy yellow flesh and downy pinkish-yellow skin.' },
  pearl: { pos: 'noun', def: 'A hard, glistening object produced within the soft tissue of a living shelled mollusk.' },
  pedal: { pos: 'noun/verb', def: 'A foot-operated lever or control for a vehicle, musical instrument, or machine.' },
  phase: { pos: 'noun/verb', def: 'A distinct period or stage in a series of events or a process of change.' },
  phone: { pos: 'noun/verb', def: 'A system or device for transmitting voices over a distance using wire or radio.' },
  photo: { pos: 'noun', def: 'A picture made using a camera, in which an image is focused onto film.' },
  piano: { pos: 'noun', def: 'A large keyboard musical instrument with a wooden soundboard and wire strings.' },
  piece: { pos: 'noun', def: 'A portion of an object or of material, produced by cutting, tearing, or breaking.' },
  pilot: { pos: 'noun/verb', def: 'A person who operates the flying controls of an aircraft.' },
  pitch: { pos: 'noun/verb', def: 'The quality of a sound governed by the rate of vibrations producing it.' },
  place: { pos: 'noun/verb', def: 'A particular position or point in space, or an area with definite boundaries.' },
  plain: { pos: 'adj/noun', def: 'Not decorated or elaborate; simple or basic in character or appearance.' },
  plane: { pos: 'noun/adj', def: 'A flat surface on which a straight line joining any two points would lie.' },
  plant: { pos: 'noun/verb', def: 'A living organism of the kind exemplified by trees, shrubs, herbs, and grasses.' },
  plate: { pos: 'noun', def: 'A flat dish, typically circular and made of china, from which food is eaten.' },
  plaza: { pos: 'noun', def: 'A public square, marketplace, or similar open space in a built-up area.' },
  pluck: { pos: 'verb/noun', def: 'To take hold of something and quickly remove it from its place.' },
  plume: { pos: 'noun', def: 'A long, soft feather or arrangement of feathers used by a bird or ornament.' },
  plump: { pos: 'adj', def: 'Having a full, rounded shape, often used as a polite term for pleasingly fat.' },
  point: { pos: 'noun/verb', def: 'A small round mark or dot, or the sharp end of a tool or weapon.' },
  polar: { pos: 'adj', def: 'Relating to the North or South Pole, or having opposite magnetic poles.' },
  porch: { pos: 'noun', def: 'A covered shelter projecting in front of the entrance of a building.' },
  power: { pos: 'noun/verb', def: 'The ability to do something or act in a particular way; physical strength.' },
  press: { pos: 'verb/noun', def: 'To apply pressure to something for a purpose such as flattening or shaping.' },
  price: { pos: 'noun/verb', def: 'The amount of money expected, required, or given in payment for something.' },
  pride: { pos: 'noun', def: 'A feeling of deep pleasure or satisfaction derived from one own achievements.' },
  prime: { pos: 'adj/noun', def: 'Of first importance; main, or of the best possible quality or condition.' },
  prism: { pos: 'noun', def: 'A solid geometric figure whose two end faces are similar, equal, and parallel rectilinear figures.' },
  prize: { pos: 'noun/verb', def: 'A thing given as a reward to the winner of a competition or race.' },
  pulse: { pos: 'noun/verb', def: 'A rhythmical throbbing of the arteries as blood is propelled through them.' },
  pupil: { pos: 'noun', def: 'A student in school or the dark circular opening in the center of the iris of the eye.' },
  queen: { pos: 'noun', def: 'The female ruler of an independent state, especially one who inherits the position.' },
  quest: { pos: 'noun/verb', def: 'A long or arduous search for something sought after or desired.' },
  quick: { pos: 'adj/adv', def: 'Moving fast or doing something in a short time; prompt.' },
  quiet: { pos: 'adj/noun', def: 'Making little or no noise; free from disturbance or commotion.' },
  quill: { pos: 'noun', def: 'Any of the main wing or tail feathers of a bird, used as an ink pen.' },
  quote: { pos: 'verb/noun', def: 'To repeat or copy out words from a text or speech written by another author.' },
  radio: { pos: 'noun/verb', def: 'The transmission and reception of electromagnetic waves carrying sound signals.' },
  rainy: { pos: 'adj', def: 'Having a great deal of rainfall; wet with falling precipitation.' },
  range: { pos: 'noun/verb', def: 'The area of variation between upper and lower limits on a scale.' },
  rapid: { pos: 'adj', def: 'Happening in a short time or at a great rate; very fast.' },
  ratio: { pos: 'noun', def: 'The quantitative relation between two amounts showing the number of times one contains another.' },
  reach: { pos: 'verb/noun', def: 'To stretch out an arm in a specified direction in order to touch or grasp.' },
  ready: { pos: 'adj/verb', def: 'In a suitable state for an activity, action, or situation; prepared.' },
  realm: { pos: 'noun', def: 'A kingdom, or a primary sphere of domain, interest, or activity.' },
  rebel: { pos: 'noun/verb', def: 'A person who rises in opposition or armed resistance against an established government.' },
  rider: { pos: 'noun', def: 'A person who is riding a horse, bicycle, or other vehicle.' },
  ridge: { pos: 'noun/verb', def: 'A long, narrow hilltop, mountain range, or elevated crest of ground.' },
  rifle: { pos: 'noun', def: 'A gun, especially one fired from shoulder level, having a rifled barrel.' },
  right: { pos: 'adj/noun', def: 'Morally good, justified, or acceptable, or the opposite direction of left.' },
  river: { pos: 'noun', def: 'A large natural stream of water flowing in a channel to the sea or lake.' },
  robot: { pos: 'noun', def: 'A machine capable of carrying out a complex series of actions automatically.' },
  rocky: { pos: 'adj', def: 'Consisting or full of rock or rocks, or unpleasantly unstable.' },
  rouge: { pos: 'noun', def: 'A red powder or cream used for coloring the cheeks or lips.' },
  round: { pos: 'adj/noun', def: 'Shaped like or approximately like a circle or cylinder; spherical.' },
  route: { pos: 'noun/verb', def: 'A way or course taken in getting from a starting point to a destination.' },
  royal: { pos: 'adj/noun', def: 'Having the status of a king or queen or a member of their family.' },
  ruins: { pos: 'noun', def: 'The physical remains of a building, city, or structure that has suffered destruction.' },
  ruler: { pos: 'noun', def: 'A person exercising government or dominion, or a straight measuring strip.' },
  rumor: { pos: 'noun', def: 'A currently circulating story or report of uncertain or unverified truth.' },
  rural: { pos: 'adj', def: 'In, relating to, or characteristic of the countryside rather than the town.' },
  saint: { pos: 'noun', def: 'A person acknowledged as holy or virtuous and regarded in heaven after death.' },
  salad: { pos: 'noun', def: 'A cold dish of various mixtures of raw or cooked vegetables.' },
  salon: { pos: 'noun', def: 'An establishment where a hairdresser, beautician, or tailor conducts business.' },
  sauce: { pos: 'noun', def: 'A liquid or semi-liquid substance served with food to add moistness and flavor.' },
  scale: { pos: 'noun/verb', def: 'Each of the small, thin plates protecting the skin of fish and reptiles.' },
  scarf: { pos: 'noun', def: 'A length or square of fabric worn around the neck or head for warmth.' },
  scene: { pos: 'noun', def: 'The place where an incident in real life or fiction occurs or occurred.' },
  scent: { pos: 'noun/verb', def: 'A distinctive smell, especially one that is pleasant or fragrant.' },
  scope: { pos: 'noun', def: 'The opportunity or possibility to do or deal with something extensive.' },
  score: { pos: 'noun/verb', def: 'The number of points, goals, or runs achieved in a game by a team.' },
  scout: { pos: 'noun/verb', def: 'A person sent out in advance of an army or group to gather information.' },
  serum: { pos: 'noun', def: 'An amber-colored, protein-rich liquid which separates out when blood coagulates.' },
  shade: { pos: 'noun/verb', def: 'Comparative darkness and coolness caused by shelter from direct sunlight.' },
  shaft: { pos: 'noun', def: 'A long, narrow part or section forming the handle of a tool or weapon.' },
  shake: { pos: 'verb/noun', def: 'To move or cause to move up and down or from side to side with rapid jerky movements.' },
  share: { pos: 'noun/verb', def: 'A part or portion of a larger amount that is divided among several people.' },
  shark: { pos: 'noun', def: 'A long-bodied chiefly marine fish with a cartilaginous skeleton and tooth-like scales.' },
  sharp: { pos: 'adj/adv', def: 'Having an edge or point that is able to cut or pierce something easily.' },
  sheep: { pos: 'noun', def: 'A domesticated ruminant animal with a thick woolly coat and typically horns.' },
  sheet: { pos: 'noun', def: 'A large rectangular piece of cotton or other fabric used on a bed.' },
  shelf: { pos: 'noun', def: 'A flat length of wood or other rigid material attached horizontally to a wall.' },
  shell: { pos: 'noun/verb', def: 'The hard protective outer case of a mollusk, turtle, or crustacean.' },
  shift: { pos: 'verb/noun', def: 'To move or cause to move from one place or position to another.' },
  shine: { pos: 'verb/noun', def: 'To emit or reflect light, and be bright or glowing with radiance.' },
  shirt: { pos: 'noun', def: 'A garment for the upper body made of cotton or silk, with a collar and sleeves.' },
  shock: { pos: 'noun/verb', def: 'A sudden upsetting or surprising event or experience that startles.' },
  shore: { pos: 'noun', def: 'The land along the edge of a sea, lake, or other large body of water.' },
  short: { pos: 'adj/adv', def: 'Measuring a small distance from end to end; not long or tall.' },
  shout: { pos: 'verb/noun', def: 'To utter a loud call or cry, typically as an expression of strong emotion.' },
  sight: { pos: 'noun', def: 'The faculty or power of seeing objects clearly using the eyes.' },
  skate: { pos: 'noun/verb', def: 'An ice skate or roller skate, or a large marine fish with a flat body.' },
  skill: { pos: 'noun', def: 'The ability to do something well; expertise acquired through training.' },
  skull: { pos: 'noun', def: 'A framework of bone or cartilage enclosing the brain of a vertebrate.' },
  slate: { pos: 'noun/adj', def: 'A fine-grained grey, green, or bluish-purple metamorphic rock easily split.' },
  sleep: { pos: 'noun/verb', def: 'A condition of body and mind that recurs naturally for several hours every night.' },
  slide: { pos: 'verb/noun', def: 'To move smoothly along a surface while maintaining continuous contact with it.' },
  small: { pos: 'adj', def: 'Of a size that is less than normal or usual; not large.' },
  smart: { pos: 'adj', def: 'Having or showing a quick-witted intelligence, or neat and conventional in dress.' },
  smile: { pos: 'noun/verb', def: 'A pleased, kind, or amused facial expression, typically with turned-up corners of mouth.' },
  smoke: { pos: 'noun/verb', def: 'A visible suspension of carbon or other particles in air, emitted from a burning substance.' },
  snake: { pos: 'noun/verb', def: 'A long limbless reptile that has no eyelids and a short tail.' },
  snare: { pos: 'noun/verb', def: 'A trap for catching birds or animals, typically one having a wire loop.' },
  solar: { pos: 'adj', def: 'Relating to, determined by, or derived from the sun and its energy.' },
  solid: { pos: 'adj/noun', def: 'Firm and stable in shape; not liquid or fluid in nature.' },
  solve: { pos: 'verb', def: 'To find an answer to, explanation for, or means of effectively dealing with a problem.' },
  sound: { pos: 'noun/adj', def: 'Vibrations that travel through the air or another medium and can be heard.' },
  south: { pos: 'noun/adj', def: 'The direction toward the point of the horizon ninety degrees clockwise from east.' },
  space: { pos: 'noun/verb', def: 'A continuous area or expanse which is free, available, or unoccupied.' },
  spark: { pos: 'noun/verb', def: 'A small fiery particle thrown off from a fire or electrical connection.' },
  speak: { pos: 'verb', def: 'To say something in order to convey information or express a feeling.' },
  speed: { pos: 'noun/verb', def: 'The rapidity in moving, travelling, or proceeding with quick velocity.' },
  spell: { pos: 'verb/noun', def: 'To write or name the letters that form a word in sequence.' },
  spice: { pos: 'noun/verb', def: 'An aromatic or pungent vegetable substance used to flavor food products.' },
  spine: { pos: 'noun', def: 'A series of vertebrae extending from the skull to the lower back.' },
  spite: { pos: 'noun/verb', def: 'A desire to hurt, annoy, or offend someone out of malice.' },
  spoon: { pos: 'noun', def: 'An implement consisting of a small, shallow oval bowl on a long handle.' },
  sport: { pos: 'noun/verb', def: 'An activity involving physical exertion and skill in which an individual competes.' },
  staff: { pos: 'noun', def: 'All the people employed by a particular organization or business enterprise.' },
  stage: { pos: 'noun/verb', def: 'A point, period, or step in a process or development of something.' },
  stair: { pos: 'noun', def: 'A set of steps leading from one floor of a building to another.' },
  stamp: { pos: 'noun/verb', def: 'A small adhesive piece of paper stuck to something to show an amount paid.' },
  stand: { pos: 'verb/noun', def: 'To have or maintain an upright position on the feet firmly.' },
  stare: { pos: 'verb/noun', def: 'To look fixedly or vacantly at someone or something with wide eyes.' },
  start: { pos: 'verb/noun', def: 'To begin doing something or performing an action in sequence.' },
  state: { pos: 'noun/verb', def: 'The particular condition that someone or something is in at a specific time.' },
  steam: { pos: 'noun/verb', def: 'The vapor into which water is converted when heated to its boiling point.' },
  steel: { pos: 'noun/adj', def: 'A hard, strong, grey alloy of iron with carbon, used in construction.' },
  stick: { pos: 'noun/verb', def: 'A thin piece of wood that has fallen or been cut from a tree.' },
  stone: { pos: 'noun', def: 'Hard solid non-metallic mineral matter of which rock is made.' },
  storm: { pos: 'noun/verb', def: 'A violent disturbance of the atmosphere with strong winds, rain, or thunder.' },
  story: { pos: 'noun', def: 'An account of imaginary or real people and events told for entertainment.' },
  stove: { pos: 'noun', def: 'An apparatus for cooking or heating that operates by burning fuel or electricity.' },
  straw: { pos: 'noun', def: 'Dried stalks of grain, used especially as fodder or bedding for animals.' },
  sugar: { pos: 'noun', def: 'A sweet crystalline substance obtained from various plants, especially sugar cane.' },
  suite: { pos: 'noun', def: 'A set of connected rooms, especially in a hotel, forming one unit.' },
  sunny: { pos: 'adj', def: 'Bright with sunlight; warm and shining with clear skies.' },
  super: { pos: 'adj/noun', def: 'Very good or pleasant; excellent in quality or degree.' },
  sweet: { pos: 'adj/noun', def: 'Having the pleasant taste characteristic of sugar or honey; not salty.' },
  swift: { pos: 'adj/noun', def: 'Happening quickly or moving with great speed and agility.' },
  sword: { pos: 'noun', def: 'A weapon with a long metal blade and a hilt with a hand guard.' },
  table: { pos: 'noun', def: 'A piece of furniture with a flat top and one or more legs.' },
  taste: { pos: 'noun/verb', def: 'The sensation of flavor perceived in the mouth and throat on contact with a substance.' },
  teach: { pos: 'verb', def: 'To impart knowledge to or instruct someone as to how to do something.' },
  teeth: { pos: 'noun', def: 'The plural of tooth; hard, white structures in the jaws used for chewing.' },
  tempo: { pos: 'noun', def: 'The speed at which a passage of music is or should be played.' },
  theme: { pos: 'noun', def: 'The subject of a talk, piece of writing, exhibition, or topic of discussion.' },
  thick: { pos: 'adj', def: 'With opposite sides or surfaces that are a great distance apart; not thin.' },
  thief: { pos: 'noun', def: 'A person who steals another person property, especially by stealth.' },
  thing: { pos: 'noun', def: 'An object to which one need not or cannot give a specific name.' },
  tiger: { pos: 'noun', def: 'A very large solitary cat with a yellow-brown coat striped with black.' },
  title: { pos: 'noun/verb', def: 'The name of a book, composition, or other artistic work.' },
  toast: { pos: 'noun/verb', def: 'Sliced bread browned on both sides by exposure to radiant heat.' },
  tooth: { pos: 'noun', def: 'Each of a set of hard, bony enamel-coated structures in the jaws.' },
  torch: { pos: 'noun/verb', def: 'A portable battery-powered electric lamp, or a stick with flaming fuel.' },
  total: { pos: 'adj/noun', def: 'Comprising the whole number or amount; complete and absolute.' },
  touch: { pos: 'verb/noun', def: 'To come into or be in contact with something physically.' },
  tower: { pos: 'noun/verb', def: 'A tall, narrow building, either freestanding or forming part of a castle.' },
  track: { pos: 'noun/verb', def: 'A rough path or road, typically one beaten by use rather than constructed.' },
  trade: { pos: 'noun/verb', def: 'The action of buying and selling goods and services between parties.' },
  trail: { pos: 'noun/verb', def: 'A mark or series of signs left behind by the passage of someone.' },
  train: { pos: 'noun/verb', def: 'A series of railway cars moved as a unit by a locomotive engine.' },
  trait: { pos: 'noun', def: 'A distinguishing quality or characteristic, typically one belonging to a person.' },
  trend: { pos: 'noun/verb', def: 'A general direction in which something is developing or changing.' },
  trial: { pos: 'noun', def: 'A formal examination of evidence by a judge, typically before a jury.' },
  tribe: { pos: 'noun', def: 'A social division in a traditional society consisting of families linked together.' },
  trick: { pos: 'noun/verb', def: 'A cunning or skillful act or scheme intended to deceive or outwit someone.' },
  troop: { pos: 'noun/verb', def: 'Soldiers or armed forces, or a group of people or animals.' },
  truck: { pos: 'noun/verb', def: 'A large, heavy motor vehicle for transporting goods or troops.' },
  truly: { pos: 'adv', def: 'In a truthful way; honestly and sincerely without falsehood.' },
  trust: { pos: 'noun/verb', def: 'Firm belief in the reliability, truth, ability, or strength of someone.' },
  truth: { pos: 'noun', def: 'The quality or state of being in accordance with fact or reality.' },
  tulip: { pos: 'noun', def: 'A bulbous spring-flowering plant of the lily family, with boldly colored cup-shaped flowers.' },
  uncle: { pos: 'noun', def: 'The brother of one father or mother or the husband of one aunt.' },
  union: { pos: 'noun', def: 'The action of joining together or the state of being joined in political unit.' },
  unity: { pos: 'noun', def: 'The state of being united or joined as a whole.' },
  vault: { pos: 'noun/verb', def: 'A secure room or compartment, typically underground, used for storage of valuables.' },
  venue: { pos: 'noun', def: 'The place where an organized event such as a concert or conference takes place.' },
  video: { pos: 'noun/adj', def: 'The recording, reproducing, or broadcasting of moving visual images.' },
  vigor: { pos: 'noun', def: 'Physical strength and good health; effortless effort and energy.' },
  virus: { pos: 'noun', def: 'An infective agent that typically consists of a nucleic acid molecule.' },
  visit: { pos: 'verb/noun', def: 'To go to see and spend time with someone socially.' },
  vital: { pos: 'adj', def: 'Absolutely necessary or important; essential for life and health.' },
  vivid: { pos: 'adj', def: 'Producing powerful feelings or strong, clear images in the mind.' },
  vocal: { pos: 'adj/noun', def: 'Relating to the human voice, or expressing opinions freely and loudly.' },
  voice: { pos: 'noun/verb', def: 'The sound produced in a person larynx and uttered through the mouth.' },
  wagon: { pos: 'noun', def: 'A vehicle used for transporting goods or another specified purpose.' },
  waste: { pos: 'verb/noun', def: 'To use or expend carelessly, extravagantly, or to no purpose.' },
  watch: { pos: 'verb/noun', def: 'To look at or observe attentively over a period of time.' },
  water: { pos: 'noun/verb', def: 'A colorless, transparent, odorless liquid that forms the seas, lakes, and rivers.' },
  wheat: { pos: 'noun', def: 'A cereal plant that is the most important kind grown in temperate countries.' },
  wheel: { pos: 'noun/verb', def: 'A circular object that revolves on an axle and is fixed below a vehicle.' },
  white: { pos: 'adj/noun', def: 'Of the color of milk or fresh snow, reflecting all light rays.' },
  whole: { pos: 'adj/noun', def: 'All of; entire; not broken, damaged, or impaired in any way.' },
  widow: { pos: 'noun', def: 'A woman who has lost her spouse by death and has not remarried.' },
  width: { pos: 'noun', def: 'The measurement or extent of something from side to side.' },
  woman: { pos: 'noun', def: 'An adult human female person; the counterpart to a man.' },
  world: { pos: 'noun', def: 'The earth, together with all of its countries, peoples, and natural features.' },
  worry: { pos: 'verb/noun', def: 'To feel or cause to feel anxious or troubled about actual problems.' },
  worth: { pos: 'noun/adj', def: 'The value equivalent to that of someone or something under consideration.' },
  wound: { pos: 'noun/verb', def: 'An injury to living tissue caused by a cut, blow, or other impact.' },
  wrist: { pos: 'noun', def: 'The joint connecting the hand with the forearm in humans.' },
  write: { pos: 'verb', def: 'To mark letters, words, or other symbols on a surface with a pen or pencil.' },
  yacht: { pos: 'noun', def: 'A medium-sized sailing or motor boat used for private pleasure cruising.' },
  yield: { pos: 'verb/noun', def: 'To produce or provide a natural, agricultural, or industrial product.' },
  young: { pos: 'adj/noun', def: 'Having lived or existed for only a short time; not old.' },
  youth: { pos: 'noun', def: 'The period between childhood and adult age; the state of being young.' },
  zebra: { pos: 'noun', def: 'An African wild horse with black-and-white stripes and an erect mane.' }
};

console.log('Total seeded EN entries in dictionary builder:', Object.keys(EN_DEFS).length);
